---
title: "Scottish Health Survey Gambling Data"
author: "Scott Kilgariff"
date: "08/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Data extracted from <a href = "https://www.gov.scot/collections/scottish-health-survey/", target = "_blank"> Scottish Health Survey </a> (SHS) covering the period from 2012 to 2017.

Data for 2021 is expected to be made available in November 2022. Questions on gambling were not included in the SHS during the years 2018 to 2020.

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(readxl)
library(httr)
library(janitor)
library(ggplot2)
library(viridis)


```

## Percentage of respondents answering "Yes" to spending money on the following, split by equivalised income
```{r grid_1, out.width = "100%", echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=10, ,results="asis"}

df_data <- read_csv("df_sheet.csv")

df_data <- df_data %>%
  filter(response_map == "Yes")

map_category <- read.csv("map_category.csv")

df_data <- df_data %>%
  left_join(map_category, by = c("category" = "category"))

df_data$measure_map <- gsub('Spent any money on:', '', df_data$measure_map)
df_data$measure_map <- gsub('Spent money on:', '', df_data$measure_map)

df_data$category_map <- ordered(df_data$category_map, 
                                levels = c('16 to 24', '25 to 34', '35 to 44', '45 to 54', '55 to 65', '65 to 74', '75 plus', 
                                           'Manager & prof.', 'Intermediate', 'Small emps & own account', 'Lower supervisory & tech.', 'Semi routine and routine', 
                                           'Top quintile earners', 'Top quintile SIMD', 'x2', 'x3', 'x4', '5th quintile earners', '5th quintil SIMD')
)

desc <- "equivalised_income"

df_data <- df_data %>% filter(description == desc)
  
for (m in seq_along(unique(df_data$measure_map))){
  
  x <- df_data %>%
    filter(measure_map == unique(df_data$measure_map)[m] &
             response_map != "Never")
  
  answer_code_list <- unique(x$answer_code)
  
  for (a in seq_along(answer_code_list)){
    y <- x %>% filter(answer_code == answer_code_list[a])

    if (nrow(y) > length(unique(y$category))*length(unique(y$response_map))*length(unique(y$sex))){
    
      p <- ggplot(y,aes(year, value)) + 
        geom_line(na.rm=TRUE) +    #removing the NA values
        geom_point(na.rm = TRUE) +
        ggtitle(paste(unique(df_data$measure_map)[m],"\n","response grouping: Equivalised Income")) +
        theme(plot.title = element_text(lineheight=.8, face="bold",size = 20)) +
        theme(text = element_text(size=10)) +
        xlab("Year") + ylab("Percentage") +
        theme_bw() +
        facet_grid(category_map ~ sex)
      print(p)
    }
  }
}


```

