---
title: "Scottish Health Survey Gambling Data"
author: "Scott Kilgariff"
date: "08/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Data extracted from <a href = "https://www.gov.scot/collections/scottish-health-survey/", target = "_blank"> Scottish Health Survey </a> (SHS) covering the period from 2012 to 2017.

Data for 2021 is expected to be made available in November 2022. Questions on gambling were not included in the SHS during the years 2018 to 2020.

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(readxl)
library(httr)
library(janitor)
library(ggplot2)
library(viridis)


```

##Number of gambling aaaaaaactivities reported by respondents
```{r grid_1, out.width = "100%", echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=10, ,results="asis"}

df_data <- read_csv("df_sheet.csv")

df_data <- df_data %>%
  filter(measure_map == "Number of gambling activities" & year > 2012)

df_data$response_map <- ordered(df_data$response_map, levels = c('Eight or more', 'Seven', 'Six', 'Five', 'Four', 'Three', 'Two', 'One', 'None'))

map_category <- read.csv("map_category.csv")

df_data <- df_data %>%
  left_join(map_category, by = c("category" = "category"))

df_data$category_map <- ordered(df_data$category_map, 
                                levels = c('16 to 24', '25 to 34', '35 to 44', '45 to 54', '55 to 65', '65 to 74', '75 plus', 
                                           'Manager & prof.', 'Intermediate', 'Small emps & own account', 'Lower supervisory & tech.', 'Semi routine and routine', 
                                           'Top quintile earners', 'Top quintile SIMD', 'x2', 'x3', 'x4', '5th quintile earners', '5th quintil SIMD')
)

for (d in seq_along(unique(df_data$description))){

    x <- df_data %>%
    filter(description == unique(df_data$description)[d])
  
  answer_code_list <- unique(x$answer_code)
  
  for (a in seq_along(answer_code_list)){
    y <- x %>% filter(answer_code == answer_code_list[a])

    if (nrow(y) > length(unique(y$category))*length(unique(y$response_map))*length(unique(y$sex))){
    
      p <- ggplot(y,aes(year, value, colour = sex)) + 
        geom_line(na.rm=TRUE) +    #removing the NA values
        geom_point(na.rm = TRUE) +
        ggtitle(paste("Number of gambling activities\n",answer_code_list[a],"\n response grouping:", unique(df_data$description)[d])) +
        theme(plot.title = element_text(lineheight=.8, face="bold",size = 20)) +
        theme(text = element_text(size=10)) +
        xlab("Year") + ylab("Percentage") +
        theme_bw() +
        facet_grid(response_map ~ category_map)+
        scale_color_manual(values=c("blue", "green","red"))
      print(p)
    }
  }
}


```

