---
title: "Scottish Health Survey Gambling Data"
author: "Scott Kilgariff"
date: "08/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Data extracted from <a href = "https://www.gov.scot/collections/scottish-health-survey/", target = "_blank"> Scottish Health Survey </a> (SHS) covering the period from 2012 to 2017.

Data for 2021 is expected to be made available in November 2022. Questions on gambling were not included in the SHS during the years 2018 to 2020.

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(readxl)
library(httr)
library(janitor)
library(ggplot2)
library(viridis)



```

## Percentage of respondents answering "Yes" to the following

```{r grid_1, out.width = "100%", echo=FALSE, message=FALSE, warning=FALSE, fig.width=10, fig.height=10, ,results="asis"}

df_data <- read_csv("df_sheet.csv")

write.csv(df_data, "df_sheet.csv")

# END

measure_list <- c("Have you gone back another day to try to win back the money you had lost?",
                  "Have you bet more than you could really afford to lose?",
                  "Have you felt that you might have a problem with gambling?")

for (d in seq_along(unique(df_data$description))){
  
  for (m in seq_along(measure_list)){
    
    x <- df_data %>%
      filter(measure_map == measure_list[m] &
               sex == "Male" &
               description == unique(df_data$description)[d] &
               #answer_code == "dsm1a (D) Answer to DSM item 1 (scale)" &
               response_map != "Never")
    
    answer_code_list <- unique(x$answer_code)
    
    for (a in seq_along(answer_code_list)){
      y <- x %>% filter(answer_code == answer_code_list[a])
      
      if (nrow(y) > length(unique(y$category))*length(unique(y$response_map))){
      
        p <- ggplot(y,aes(year, value)) + 
          geom_line(na.rm=TRUE) +    #removing the NA values
          geom_point(na.rm = TRUE) +
          ggtitle(paste(measure_list[m],"\n",answer_code_list[a])) +
          theme(plot.title = element_text(lineheight=.8, face="bold",size = 20)) +
          theme(text = element_text(size=10)) +
          xlab("Year") + ylab("Percentage") +
          theme_bw() +
          facet_grid(category ~ response_map)
        print(p)
      }
    }
  }
}

```

